name: envlipidhunter
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - cython
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl_fft
  - mkl_random
  - natsort
  - numba
  - numpy
  - numpy-base
  - openpyxl
  - openssl
  - pandas=0.23.*
  - pip
  - plotly
  - pyopenssl
  - pyside=1.2.4
  - python=3.6.*
  - python-dateutil
  - setuptools
  - scipy
  - sip
  - six
  - xlrd
  - xlwt
  - pip:
    - pymzml==0.7.8