name: envlipidhunter
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - cython
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl_fft
  - mkl_random
  - natsort
  - numba
  - numpy=1.11.3
  - numpy-base=1.11.3
  - openpyxl
  - openssl
  - pandas=0.23.4
  - pip
  - plotly
  - pyopenssl
  - pyside=1.2.4
  - python=3.6.*
  - python-dateutil
  - setuptools
  - scipy=1.2.1
  - sip
  - six
  - xlrd
  - xlwt
  - pip:
    - pymzml==0.7.8