name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - boost=1.66.0
  - boost-cpp=1.66.0
  - ca-certificates=2019.1.23
  - cairo=1.14.12
  - cython=0.28.5
  - ipython_genutils=0.2.0
  - libpng=1.6.34
  - llvmlite=0.24.0
  - lxml=4.2.3
  - matplotlib=2.0.0
  - mccabe=0.6.1
  - mkl=2019.0
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - natsort=5.4.0
  - numba=0.39.0
  - numexpr=2.6.6
  - numpy=1.14.2
  - openpyxl=2.5.8
  - openssl=1.0.2p
  - pandas=0.23.4
  - pillow=5.2.0
  - pip=10.0.1
  - plotly=3.3.0
  - pyside=1.2.4
  - python=3.6.6
  - scipy=1.1.0
  - six=1.11.0
  - xlrd=1.1.0
  - xlwt=1.3.0
  - pip:
    - pymzml==0.7.8
    - pypiwin32==223
    - python-dotenv==0.10.1


